# Use the official Nginx image as the base image
FROM nginx:latest

# Copy the static website files to the appropriate location in the container
COPY 

# Expose port 80 to the host
EXPOSE 80

# Nginx runs on port 80 by default, so no need to specify CMD
